### ISSUE TITLE
[Plug-in] Divulgação científica

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#100]
![div 3](https://user-images.githubusercontent.com/32966068/41933684-f63d3808-795a-11e8-8438-d4b6fe0e41d5.png)

- [ ] Imagem
- [ ] Título
- [ ] Texto
- [ ] URL (paginas interna)

**Comment by WellisonRodrigues** [comment]
Nesta issue falta verificar a possibilidade de melhorar a experiencia do usuario no cadastrado de urls internas
