### ISSUE TITLE
[Front-end] Logo e vídeo

### ISSUE THREAD

**Issue by arturpr** [Fapemig/site-app#11]

**Comment by luizlgam** [comment]
Falta colocar o link para download dos arquivos.

**Comment by luizlgam** [comment]
Falta linkar os estilos feitos na página, com o 'static'

**Comment by WellisonRodrigues** [comment]
Favor verificar os itens destacados
![image](https://user-images.githubusercontent.com/32049857/41293780-a34cbd5a-6e2c-11e8-9d23-36ac36e00bea.png)
