### ISSUE TITLE
[ADMIN]- Sala de imprensa / Revista

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#138]
Criar:

- [ ] Model gerenciável pelo ADMIN
1. Imagem
2. Título
<del>3. Categoria</del
4. Link da visualização do PDF issuu.com
(por agora, iremos utilizar um recurso externo para gerar a visualização, posteriormente iremos usar recurso próprio)
5. Arquivo (sobe o arquivo, mas gerar link também de fácil para download)

- [ ] Publisher

![revista](https://user-images.githubusercontent.com/32966068/45489369-7133b380-b73a-11e8-9306-d8f09e44c137.png)

**Comment by kelvinfrade** [comment]
Tem que confirmar se é apenas um link para redirecionar.

**Comment by luizlgam** [comment]
Foram levantados problemas, que serão avaliados posteriormente.
- Verificar Categorias
- Não há acesso ao código do iframe

**Comment by shfrade** [comment]
Link de uma visualização funcionando:
# default
<div data-configid="34553371/64473992" style="width:525px; height:350px;" class="issuuembed"></div>
<script type="text/javascript" src="//e.issuu.com/embed.js" async="true"></script>

# iframe
<iframe style="width:525px; height:350px;" src="//e.issuu.com/embed.html#34553371/64473992" frameborder="0" allowfullscreen></iframe>
