### ISSUE TITLE
[Front-end] Criar template / Sala de imprensa / Revista

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#140]
Criar template da página:
![8](https://user-images.githubusercontent.com/32966068/42289378-76e8cca2-7f95-11e8-9287-67112f1fe3e5.png)

1. Listar todas as revistas. #139 e #138
![image](https://user-images.githubusercontent.com/32966068/42289414-ad91067a-7f95-11e8-89f3-abc0b653137c.png)

2. Exibir e deixar ver a revista selecionada do item anterior.
![image](https://user-images.githubusercontent.com/32966068/42289418-b2c54fde-7f95-11e8-8c2e-76a0cb3bd0c7.png)

**Comment by kelvinfrade** [comment]
https://issuu.com/fapemig/docs/mfc_69__final
