### ISSUE TITLE
Criar ambiente de homologação

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#147]
Criar um novo ambiente para produção-
release

- [x] Replicar dados já cadastrados do site-app

**Comment by shfrade** [comment]
Agora existe como release:
http://site-app.fapemig.br/pt/
E o dev:
http://site-app-dev.fapemig.br/pt/

O do azure ainda não foi feito, necessário verificar a liberação de algumas portas pela PRODEMGE assim como verificar como publicar o nome dele na internet com as novas configurações na AZURE.

**Comment by arturpr** [comment]
Para a Sprint 6 essa issue  vale 7 pontos
