### ISSUE TITLE
[Documentação] Tamanhos de fotos a serem utilizados

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#155]
Levantar e documentar o tamanho de fotos utilizadas nas telas.
Deve ser gerado um manual/documentação sobre isso.

**Comment by vantuiroliveira** [comment]
Levantamento dos tamanhos das imagens no site FAPEMIG.
[Levantamento tamanho imagens site FAPEMIG.docx](https://github.com/Fapemig/site-app/files/2279310/Levantamento.tamanho.imagens.site.FAPEMIG.docx)
