### ISSUE TITLE
[Cadastro-cms] Cadastrar conteúdo da página - Resultados

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#181]
Requerimento: #175 e #180 
![image](https://user-images.githubusercontent.com/32966068/42636398-1cc72216-85bf-11e8-9c9f-61aa9cae548c.png)

**Comment by WellisonRodrigues** [comment]
Foi cadastrado apenas parte do conteudo, como possui muitos editais a serem cadastrados esta tarefa ficara a cargo do propio departamento responsavel por gerir o conteudo.
