### ISSUE TITLE
[Cadastro-cms] Cadastrar conteúdo da página - Editais encerrados

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#183]
Requerimento: #175 e #182 
![image](https://user-images.githubusercontent.com/32966068/42636514-610e4918-85bf-11e8-94de-454f903b6811.png)

**Comment by andersonmereu** [comment]
Cadastro Feito, mas algumas observações vistas ao cadastrar:

- Como o botão download não tem como colocar fora do card cinza escuro, acho melhor retirar e deixar só o claro.

- A template do ficheiro não aceita abrir em nova janela.

- O limite de caracteres para subtitulo esta pequeno.
