### ISSUE TITLE
Site map

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#202]
Final de projeto
![image](https://user-images.githubusercontent.com/32966068/42692856-7c25842c-8683-11e8-8004-cb6e354aa3b1.png)

- [x] Linkar e confirmar.
- [x] Adicionar comissão de etica.

**Comment by WellisonRodrigues** [comment]
verificar novamente os links, deixar exatamente igual, e verificar direcionamentos da sala de imprensa.

**Comment by shfrade** [comment]
Criar "Comunicados na "Sala de imprensa"

**Comment by shfrade** [comment]
1) Ajustar o "Assine revista minas faz ciencia" 
2) Criar links do fale conosco conforme issue #347.
