### ISSUE TITLE
Estender plugin ficheiro com o tema em LISTA

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#211]
Cadastrar o tema abaixo na lista de template para o plugin FICHEIRO
![image](https://user-images.githubusercontent.com/32966068/42884583-17ad1c80-8a75-11e8-9f2d-4e54e869fd68.png)

**Comment by WellisonRodrigues** [comment]
Documentação de uso encontrado para este tipo:

https://github.com/divio/djangocms-file/blob/master/djangocms_file/templates/djangocms_file/default/file.html
