### ISSUE TITLE
[Back-end] Plug-in Área

### ISSUE THREAD

**Issue by arturpr** [Fapemig/site-app#24]
- [x] Montar o Model
- [x] Montar o Publisher

**Comment by shfrade** [comment]
Feito

**Comment by vantuiroliveira** [comment]
![image](https://user-images.githubusercontent.com/38473287/41306317-19b30854-6e4c-11e8-8140-aa8a024fc6b5.png)

Verificar...
Seguindo o modelo acima, a sigla do departamento deve ficar após o nome do mesmo, (entre parênteses).

Porém por não usar a sigla em seu campo de origem (SIGLA DO SETOR) no plugin, é exibido texto "None".

![image](https://user-images.githubusercontent.com/38473287/41306378-5242f288-6e4c-11e8-90ce-3cd230f5a444.png)
