### ISSUE TITLE
Treinamento - Criar documentação

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#277]
Criar documentação do treinamento:
1. Ações básicas (recuperar senha, logar, editar página)
- [ ] Recuperar senha, logar (3 pts, sprint 7) completado no dia 25/08
- [ ] Começar modo editar em uma página (  )
2. Ações avançadas (criar páginas, alterar páginas, criar sub-páginas)
- [ ] Criar páginas (  )
- [ ] Alterar template e definições avançadas
- [ ] Criar sub-páginas
3. Criação de plugin's por menu
- [ ] Menu institucional (24pts - Sprint 8) completado no dia 10/09
- [ ] Menu Serviços
- [ ] Menu Linhas de fomento
- [ ] Menu Chamadas
- [ ] Menu Sala de imprensa
- [ ] Menu Fale Conosco

**Comment by shfrade** [comment]
Para não gerar o mesmo arquivo N vezes, ela esta sendo feita em UMA issue apenas, ao invés de dividi-la em N partes.

**Comment by vantuiroliveira** [comment]
Processo de Documentação do "Menu Institucional" do Site FAPEMIG, caminhando para fase final.
