### ISSUE TITLE
Treinamento - aulas ACS

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#278]
Treinamento com o pessoal da ACS:

Funções:
notícias,   vídeos, projeto MFC, áreas não atualizadas por outros setores

**Comment by vantuiroliveira** [comment]
Treinamento Realizado com :
ACS-Assessoria de Comunicação Social
•	Usuário (s)
•	Carol Ferreira;
•	Lucas Costa;
•	Luiz Boareto;
•	Rodrigo Silva;
•	Tatiana;
•	Teo (Minas Inova);
•	Vanessa Fagundes;
- Notícias, Vídeos, Projeto MFC;
- Áreas não atualizadas por outros setores;
