### ISSUE TITLE
Treinamento - DAPP

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#280]
Funções:
Chamadas/Abertas,   análise, encerradas, resultados + Serviços/formulários e tabelas vigentes

**Comment by vantuiroliveira** [comment]
Treinamento Realizado:
**DAPP-Departamento de Análise de Propostas de Projetos**
•	Usuário (s)
•	Ader Dias;
•	Paula Oliveira;
- Menu Chamadas
- Chamadas: Abertas – Análise – Resultados – Encerradas
- Menu Serviços
- Formulários e Tabelas Vigentes
