### ISSUE TITLE
Treinamento - DBET

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#281]
Funções:
Chamadas/Abertas,   análise, encerradas, resultados

**Comment by vantuiroliveira** [comment]
Treinamento Realizado com :
DBET - Departamento de Programa de Bolsas e Eventos Técnicos
•	Usuário (s)
•	Anubia Palma;
•	Fernanda Cristina;
•	Jucimar;
•	Maria Correa;
•	Vandeci;
- Menu Chamadas
- Módulo Oportunidades FAPEMIG
- Chamadas: Abertas – Análise – Resultados - Encerradas
