### ISSUE TITLE
Treinamento - DEPI

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#283]
Funções:
Chamadas/Abertas,   análise, encerradas, resultados

**Comment by vantuiroliveira** [comment]
Treinamento Realizado com :
DEPI - Departamento de Relações Empresariais e Propostas de Inovação
•	Usuário (s)
•	Aloysio Santos;
•	Camila Santos;
- Menu Chamadas
- Módulo Oportunidades FAPEMIG
- Chamadas: Abertas – Análise – Resultados - Encerradas
