### ISSUE TITLE
Treinamento DPC

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#285]
Funções:
Serviços/formulários/prestação   de contas

**Comment by vantuiroliveira** [comment]
Treinamento Realizado com:
DPC - Departamento de Prestação de Contas
•	Usuário (s)
•	Alexandre de Jesus Machado
•	Guilherme Dias Campos Barbosa
- Menu Serviços
- Módulo Formulários 
- Prestação de Contas
