### ISSUE TITLE
Treinamento - DPI

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#289]
Funções:
Serviços/parcerias   internacionais + Chamadas (abertas, análise, encerradas, resultados) +   Chamadas (oportunidades via Confap)

**Comment by vantuiroliveira** [comment]
Treinamento Realizado:
DPI-Departamento de Parcerias Internacionais
•	Usuário (s)
•	Marina Brini
•	Ana Boas
•	Luísa Rates
- Menu Serviços;
- Parcerias Internacionais;
- Menu Chamadas;
- Oportunidades FAPEMIG (Abertas - Análise - Resultados - Encerradas); 
- Oportunidades CONFAP (Abertas - Análise - Resultados - Encerradas);
