### ISSUE TITLE
[Front-end] Visita

### ISSUE THREAD

**Issue by jdmmiranda307** [Fapemig/site-app#349]
Criar o formulário de visita, que enviará os dados por meio de uma requisição POST para uma API.
/visitas/add_externo
![5 visita](https://user-images.githubusercontent.com/22590528/46027647-bfdf3700-c0c4-11e8-94a4-c809e61afd7b.png)

**Comment by jdmmiranda307** [comment]
Nomes dos campos esperados:

- nome
- email
- telefone
- gestora
- instituicao
- numero_processo
- assunto
- sugestao_data_horario

**Comment by WellisonRodrigues** [comment]
"nome=uashduiashdu&email=auisdh%40AIUSDHUIAS.com&telefone=23123132&gestora=auihsduiahs&instituicao=uiahsuidah&numero_processo=4122132&assunto=ausduiahsd"

**Comment by jdmmiranda307** [comment]
https://stackoverflow.com/questions/23287067/converting-serialized-forms-data-to-json-object
