### ISSUE TITLE
[Front-end] Plug-in pessoa

### ISSUE THREAD

**Issue by arturpr** [Fapemig/site-app#4]
Elaborar Front-end para plug-in de pessoas, que será utilizado na página **Quem é quem**.

![image](https://user-images.githubusercontent.com/7481902/40030847-2a5c6398-57c3-11e8-932d-5bf5bfc72664.png)

**Comment by WellisonRodrigues** [comment]
![image](https://user-images.githubusercontent.com/32049857/41179288-9ee2c956-6b40-11e8-9d3a-7b620518a2c3.png)

1- Imagem não aparece (Deve ser tratado também caso não exista)
2- Alinhar titulo a esquerda acompanhando o alinhamento do texto do menu, Reduzir o tamanho da fonte com tamanho aproximado do prototipo, Cor da fonte: #4DB7BC
3- Alinhar titulo a esquerda acompanhando o alinhamento do texto do menu
4- Cor da fonte: #4DB7BC
5- Remover tag HR
6- Remover tag HR
7- Nome deve ser depois do campo função (verificar no prototipo), cor da fonte: #20608F
8- Letra maiuscula, cor da fonte: #4DB7BC

Segue imagem do prototipo para consulta:
![image](https://user-images.githubusercontent.com/32049857/41179931-e1c66474-6b42-11e8-9f1c-28b11acdc129.png)
