### ISSUE TITLE
Depois da migração

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#420]
- [x] Conferir links:
1. Transparência:
![image](https://user-images.githubusercontent.com/32966068/47021882-bc265980-d132-11e8-9b0a-91ca0c75d04d.png)

-  Sobre  a lei de acesso, letra C
-  Ações e programas: confira os programas 
-  Ações e programas: DEER

2. Linhas de fomento, conferir todos os cards.
3. Conferir link da comissão de Etica
4. Atualizar link do MANUAL DA FAPEMIG, apontar para o FALE CONOSCO
http://site-app-prd.fapemig.br/pt/menu-servicos/instituicoes-cadastradas/
![image](https://user-images.githubusercontent.com/32966068/47586554-ef3cca00-d936-11e8-8129-5c6aa2a30d24.png)
5. Conferir link das instituições cadastradas (imagem acima)

**Comment by luizlgam** [comment]
Email solicitando arquivos enviado para Vanessa ACS no dia 05/11/2018

**Comment by shfrade** [comment]
antigosite.fapemig.br para conferir os arquivos.
