### ISSUE TITLE
Bugs 06-11-2018

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#518]
- [x] Conselho curador, fotos do mesmo tamanho. 
Conferir tamanho e alinhar com ACS para o devido preenchimento.
- [x] Instituições cadastradas - tamanho
![image](https://user-images.githubusercontent.com/32966068/48082073-ba533180-e1d8-11e8-941e-e33683c3437e.png)
- [x] Instituições cadastradas - paginação não acompanha o filtro
- [x] Instituições cadastradas - criar um modal mostrando o PORQUE da inadimplência
![image](https://user-images.githubusercontent.com/32966068/48083474-66e2e280-e1dc-11e8-9541-361f8736ecb9.png)
- [x] Contato ACS - erro 500
![image](https://user-images.githubusercontent.com/32966068/48082128-e078d180-e1d8-11e8-9c0d-b85d205af5ce.png)
- [x] Links com "Veja mais" abrir na mesma página.
- [x] Pedir a ACS para cadastrar mais um álbum
- [x] Pedir a ACS nas noticias, para utilizarem a fonte que é utilizada no site. Ver no CSS.
- [x] Pedir a ACS para padronizar o tamanho das fotos do conselho curador. (ver tamanho e informa-los)
- [x] Pedir a ACS pedir para padronizar as imagens das noticias, NÃO USAR IMAGENS COM FUNDO BRANCO!!!
- [x] Ajustar texto da clientela.
- [x] Ajustar o mapa, alinhar e centralizar correspondente ao país. 
- [x] Verificar se tem alguma "MEDIA" quebrando por permissão, ver nas imagens das noticias.
- [x] Verificar com Elerson sobre o PHL (biblioteca, como funciona)
- [x] Logo da home quando fica com resolução baixa, corrigir o link.
![image](https://user-images.githubusercontent.com/32966068/48082448-cd1a3600-e1d9-11e8-9c22-c3250324ef5c.png)
- [x] Criar HOME para diferentes resoluções. Tablet, celular e notebook.
Conferir as bordas.
- [x] Conferir tamanho das margens laterais em todas as resoluções.
- [x] Conferir issues abertas, se já estiver concluída ou mencionada aqui. Fechar ela.
- [x] Adicionar summernote no noticias/comunicados
- [ ] Linkar o botão do banner 
- [x] Fazer a tela que falta: #78 e #117 
- [x] Ajustar os formulários do para funcionar o template corretamente no Internet Explorer.
- [ ] Paginação com filtro (Notícias, Compras e Licitações e Perguntas Frequentes).
- [x] Cor do botão categoria no carrocel da Home fica branco no MAC.
- [ ] Colocar número do edital nas chamadas da Home e verificar a quantidade que está mostrando.
- [x] Arrumar banner cortando botão e alinhamento da capa da revista na Home.

**Comment by shfrade** [comment]
Adicionar filtro de pesquisa em:
- [ ] Perguntas frequentes:
![image](https://user-images.githubusercontent.com/32966068/48132347-5d0fbc80-e27a-11e8-990d-235a6b412910.png)
- [ ] Fale conosco - manuais
![image](https://user-images.githubusercontent.com/32966068/48132373-731d7d00-e27a-11e8-8556-f66801c7df48.png)

**Comment by luizlgam** [comment]
Não é possível reposicionar os ícones do mapa, pois o mapa é uma imagem fixa.

**Comment by shfrade** [comment]
Sobre as noticias (home)
- [ ] Ver quantidade de caracteres, e tentar unificar isto entre estas duas partes.
![image](https://user-images.githubusercontent.com/32966068/48414137-f6364b80-e730-11e8-80f7-31b047363415.png)
![image](https://user-images.githubusercontent.com/32966068/48414162-0cdca280-e731-11e8-9c8a-5777dd38a8e8.png)
- [ ] Não justificar o texto, e passar para a Vanessa ver como ficou para ver se realmente não quer manter isso.
![image](https://user-images.githubusercontent.com/32966068/48414166-10702980-e731-11e8-9086-19eb553df12b.png)

**Comment by luizlgam** [comment]
Realizadas as mudanças de texto e áreas dos mapas de parcerias internacionais solicitadas por Luisa Gouvea
