### ISSUE TITLE
Conferir Responsividade do site por menus

### ISSUE THREAD

**Issue by luizlgam** [Fapemig/site-app#576]
Teste:

- Navegadores: Chrome, Firefox
- Resoluções: Todas de inspeção do navegador

Responsáveis:

@kelvinfrade : 
- [x] Serviços, 
- [x] Home

@luizlgam : 
- [x] Chamadas
- [x] , Institucional

@shfrade : 
- [x] Menu Superior

@vantuiroliveira : 
- [x] Fale Conosco,
- [x]  Linhas de Fomento
- [x]  Sala de Imprensa

@WellisonRodrigues :
- [x] Biblioteca

Anotem pontos que não ficaram bons e em quais resoluções,  para podermos mapear e começar a resolver os problemas de responsividade.

**Comment by vantuiroliveira** [comment]
Levantamento dos tópicos responsivos no site da FAPEMIG, usando os navegadores:
**Chrome e Firefox**

- Fale Conosco
- Linhas de Fomento
- Sala de Imprensa

[Site_Fapemig_Responsive.docx](https://github.com/Fapemig/site-app/files/2685826/Site_Fapemig_Responsive.docx)

**Comment by shfrade** [comment]
# Geral
- [ ] Menu que aparece na resolução tablet para baixo
![image](https://user-images.githubusercontent.com/32966068/50150041-fda6c280-02a3-11e9-9c16-49b763f9b65e.png)
- [ ] Falta um espaço em "Demonstrativo Desp. Pessoal"
- [ ] Em 1368 para baixo, a pipeline após "Demonstrativo Desp. Pessoal" perde o sentido.
![image](https://user-images.githubusercontent.com/32966068/50150587-90942c80-02a5-11e9-8c18-ffc73c433191.png)
![image](https://user-images.githubusercontent.com/32966068/50150605-9d188500-02a5-11e9-8f79-542b1eb3c2f2.png)
![image](https://user-images.githubusercontent.com/32966068/50150621-a4d82980-02a5-11e9-9a25-2812d161b36f.png)
![image](https://user-images.githubusercontent.com/32966068/50150666-c89b6f80-02a5-11e9-87f1-744c5266a9be.png)




# http://site-app-dev.fapemig.br/pt/manuais/
- [ ] Fonte não esta quebrando automaticamente
![image](https://user-images.githubusercontent.com/32966068/50150107-2929ad00-02a4-11e9-8b4a-8ccb68f33dca.png)
- [ ] Por causa do item anterior ele acaba extendo a tela, extrapolando o site em todas as resoluções abaixo de tablet.
![image](https://user-images.githubusercontent.com/32966068/50150202-668e3a80-02a4-11e9-9bf4-b195041c6238.png)
![image](https://user-images.githubusercontent.com/32966068/50150244-77d74700-02a4-11e9-908b-7c51d01030af.png)
- [ ] Estourando erro também.
![image](https://user-images.githubusercontent.com/32966068/50150259-83c30900-02a4-11e9-800f-a63f6ad0da1d.png)
# http://site-app-dev.fapemig.br/pt/gestoras-credenciadas/
- [ ] Por causa da tabela, conteúdo não fica responsivo.
Sugestão: colocar cada item da tabela como linha de um card para ver se fica bom quando a resolução for de celular.
![image](https://user-images.githubusercontent.com/32966068/50150441-267b8780-02a5-11e9-8133-7b5230aff90e.png)

**Comment by luizlgam** [comment]
- [ ] Menu Chamadas , legenda da imagem está sendo cortada em mobile
![chamadas](https://user-images.githubusercontent.com/17342602/50897353-026a1c80-13f3-11e9-9ccd-fbea8c3e1380.jpg)

**Comment by kelvinfrade** [comment]
A Home Responsiva está sendo desenhada pela Daiana, quando ficar pronto o desenho faremos a readequação.

**Comment by kelvinfrade** [comment]
Desenho da Home Mobile:
![iphone 6-7-8 plus 1](https://user-images.githubusercontent.com/5895584/51476750-9205b880-1d6d-11e9-9724-ab04ea748c36.png)
![iphone 6-7-8 plus 2](https://user-images.githubusercontent.com/5895584/51476751-9205b880-1d6d-11e9-9f49-a05ce883238e.png)

**Comment by kelvinfrade** [comment]
Home para Tablet:
![tabletfapemig](https://user-images.githubusercontent.com/5895584/51553354-c48cdf80-1e59-11e9-9b69-9bbebe3029de.png)
