### ISSUE TITLE
Conferir tags para noticias serem públicadas no facebook, twitter e instagram com "previa"

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#594]
- [x] Conferir tags para noticias serem públicadas no facebook, twitter e instagram com "previa"
Exemplo se for uma noticia da globo:

https://g1.globo.com/economia/tecnologia/noticia/2018/12/20/numero-de-internautas-cresce-em-cerca-de-10-milhoes-em-um-ano-no-brasil-aponta-ibge.ghtml
![image](https://user-images.githubusercontent.com/32966068/50298953-87eb5400-0467-11e9-9072-99cd15a28b71.png)

http://fapemig.br/pt/noticias/90/
![image](https://user-images.githubusercontent.com/32966068/50299007-acdfc700-0467-11e9-81d1-feacd5be8dfd.png)

**Comment by kelvinfrade** [comment]
Resolvido! Mandei e-mail para Tuany da ACS fazer os testes.
