### ISSUE TITLE
02/01 até 30/01

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#623]
# Testes dos membros de câmara como MODEL ao invés de plugin
- [x] Criar models
- [x] Criar registro no admin
- [x] Criar View 
- [x] Criar template (+ trabalho artístico do Kelvin)
- [x] Testar se esta ORDENADO automaticamente e com a linha da coordenadora abaixo do registro correto.
- [x] Apresentar solução ao Flávio e Betânia

# Treinamento da Compra e Licitação e Chamadas
- [x] Manual Chamada
- [x] Manual Compra e Licitação
- [x] Treinamento Chamada
- [x] Treinamento Compra e Licitação
# Permissões - Alterar permissões dos usuários e grupos, para corresponder o que de fato precisam.
- [x] ACS
- [x] Conselho curador
- [x] DCI
- [x] DAPP
- [x] DBET
- [x] DCC
- [x] DEPI
- [x] DGP
- [x] DPC
- [x] DPIT
- [x] GCT
- [x] GIN
- [x] DPI
- [x] Procuradoria
- [x] SCA 
# Biblioteca
- [x] Prototipagem das telas
- [x] Apresentação da prototipagem das telas para o setor responsável 
- [x] Apresentação da prototipagem das telas para o Flávio
- [x] Criação do modelo de banco de dados
- [x] Passar as normas no modelo de banco de dados. https://pt.wikipedia.org/wiki/Normaliza%C3%A7%C3%A3o_de_dados
- [x] Implementar no modelo físico
- [x] Criação das telas (regras de negocio)
- [x] Estilização das telas (estilo)
- [x] Colocar em produção.

**Comment by luizlgam** [comment]
Camaras de Assessoramento refeito com API.

**Comment by luizlgam** [comment]
Ordenação primeiro pelo coordenador, depois membros solicitada pelo Flávio.

**Comment by kelvinfrade** [comment]
Prototipagem das telas do sistema da biblioteca, em PDF e o editável em ZIP:

[Prototipagem de Telas Biblioteca.pdf](https://github.com/Fapemig/site-app/files/2784354/Prototipagem.de.Telas.Biblioteca.pdf)


[Prototipagem de Telas da Biblioteca.zip](https://github.com/Fapemig/site-app/files/2784358/Prototipagem.de.Telas.da.Biblioteca.zip)

**Comment by luizlgam** [comment]
Aguardando testes de utilizadores do sistema da biblioteca.
