### ISSUE TITLE
Implantação de SSL (Converter rotas http para htttps)

### ISSUE THREAD

**Issue by WellisonRodrigues** [Fapemig/site-app#687]
Substituir rotas ajax que consomem o everest para serem tratas no django, o consumo deverá ser feito no servidor e não no cliente, uma vez que o everest não ira possuis SSL.

**Comment by luizlgam** [comment]
Converter urls do sistema ci para https
Mudanças:
Áreas de atuação/ Instituições Cadastradas

Mudar Urls de apis internas para https

**Comment by luizlgam** [comment]
Agora as requisições estão sendo realizadas pelo python e depois consumidas pelo js.
Falta realizar os testes quando o ssl for aplicado.

**Comment by luizlgam** [comment]
Testes realizados e concluidos com êxito.
