### ISSUE TITLE
[Cadastro CMS] Quem é quem

### ISSUE THREAD

**Issue by arturpr** [Fapemig/site-app#7]
Atualizar os dados reais da página

**Comment by vantuiroliveira** [comment]
QUEM É QUEM
•	Retirar o Título: DIRETORIA EXECUTIVA do plugin (Pessoa Plugin);
•	Incluir um Container no plugin (Pessoa Plugin) para conter as fotos;
•	Alinhar altura das fotos/container em relação aos campos à direita da mesma;
•	Em relação aos campos à direita da foto, manter o (CONTATO), como se fosse um footer;
•	Nos tópicos (COORDENADORIAS ADJUNTAS, ASSESSORIAS E GERÊNCIAS e DEPARTAMENTOS):
o	 Fazer a distribuição do conteúdo na horizontal;
o	Alinhar o texto em referência ao título dos tópicos;
o	Remover a opção (SIGLA DO SETOR) do plugin (Setor Funcionario Plugin), uma vez que o modelo apresenta a sigla entre parênteses após o nome do setor;
