### ISSUE TITLE
Verificar com acs mudanças em sala de imprensa 

### ISSUE THREAD

**Issue by luizlgam** [Fapemig/site-app#866]
Slide 74

**Comment by kelvinfrade** [comment]
/home/kelvin/Pictures/sala de imprensa.png

**Comment by kelvinfrade** [comment]
![sala de imprensa](https://user-images.githubusercontent.com/5895584/55582264-63a14380-56f5-11e9-8ddd-940ce0ef2ac6.png)

**Comment by luizlgam** [comment]
Email enviado, aguardando resposta.

**Comment by luizlgam** [comment]
De acordo com o email recebido, não há nenhuma mudança a ser realizada.
