### ISSUE TITLE
Espaçamento collapse manuais / Fale conosco 

### ISSUE THREAD

**Issue by luizlgam** [Fapemig/site-app#869]

**Comment by kelvinfrade** [comment]
![image](https://user-images.githubusercontent.com/5895584/55582423-d4486000-56f5-11e9-9d65-e66d32b76656.png)

**Comment by luizlgam** [comment]
As Informações sobre a fapemig estão sendo carregadas a partir do sistema da CI.
As informações devem ser alteradas nesse sistema.
