### ISSUE TITLE
[Front-end + Cadastro] Template Parcerias internacionais

### ISSUE THREAD

**Issue by shfrade** [Fapemig/site-app#97]
![21](https://user-images.githubusercontent.com/32966068/41932758-4a0b8014-7958-11e8-9a52-bd39129c0fd0.png)
![22 - parcerias internacionais](https://user-images.githubusercontent.com/32966068/41933037-1f8c13d4-7959-11e8-97bc-7162753ec6b8.png)

Como fazer o mapa da melhor maneira.

**Comment by arturpr** [comment]
Para a Sprint 6 essa Issue vale 8 pontos
